from list_and_card_def import List
from time import sleep

list = List('title')
print(list.title)
first_card = list.add('card')
print(first_card.text)
first_card.timer_start()
sleep(2)
# print("elapsed time(active): %s" %card.elapsed_time())
# print(card.status)
first_card.timer_end()
first_card.timer_start()
sleep(2)
first_card.timer_end()
print("elapsed time(inactive): %s, status: %s, log: %s" %(first_card.elapsed_time(), first_card.status, first_card.log))
# print("first_card total elapsed time: %s" %first_card.total_time_elapsed())
second_card = list.add()
print('second card')
second_card.timer_start()
sleep(1)
print(second_card.elapsed_time())
print('first card: %s, second: %s' %(first_card.status, second_card.status))
second_card.timer_end()
print("second card log: %s, total_time_elapsed: %s" %(second_card.log, second_card.total_time_elapsed()))
# print("are they equal? %s" %(first_card.log[1] == second_card.log[1]))
print("total time elapsed in list: %d" %list.total_time_elapsed())
print("cards: %s" %list.cards)

#expect about 5 seconds total_time_elapsed
